### ISSUE TITLE
Build failure with ansi-terminal-0.7

### ISSUE THREAD

**Issue by DanBurton** [yamadapc/list-prompt#3]
Apparently `SGR` is no longer an instance of Ord (?)

Build failure as seen on the stackage build server:

```
[1 of 3] Compiling System.Console.ListPrompt.Types ( lib/System/Console/ListPrompt/Types.hs, dist/build/System/Console/ListPrompt/Types.o )

lib/System/Console/ListPrompt/Types.hs:10:18: error:
    • No instance for (Ord SGR)
        arising from the first field of ‘ListPromptOptions’ (type ‘[SGR]’)
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (Ord ListPromptOptions)
   |
10 |   deriving(Show, Ord, Eq)
   |                  ^^^
```

**Comment by DanBurton** [comment]
Apologies for the short notice, but I've removed list-prompt from the stackage nightly builds in order to allow for ansi-terminal-0.7. Please feel free to send a PR reverting this commit (https://github.com/fpco/stackage/commit/31086613ff9e9642e064919fd04e8cdca0e3c014) once a version of list-prompt is released that builds with ansi-terminal-0.7.
